### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [Modflower/QuickBench#8]
Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_3955.method_8116(net.minecraft.class_1263, net.minecraft.class_5455)'
        at tfar.fastbench.MixinHooks.slotChangedCraftingGrid(MixinHooks.java:61) ~[quickbench-4.3.0+mc.1.20.4.jar:?]
        at net.minecraft.class_1714.md08e4ba$quickbench$lambda$slotsChanged$0$0(class_1714.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_3914.method_17394(class_3914.java:35) ~[server-intermediary.jar:?]
        at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3914.method_17393(class_3914.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_1714.method_7609(class_1714.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1715.redirect$bhk000$quickbench$checkForChanges(class_1715.java:563) ~[server-intermediary.jar:?]
        at net.minecraft.class_1715.method_5447(class_1715.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_7673(class_1735.java:75) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_48931(class_1735.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_53512(class_1735.java:63) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7616(class_1703.java:661) ~[server-intermediary.jar:?]
        at net.minecraft.class_1714.method_7601(class_1714.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_30010(class_1703.java:394) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12076(class_3244.java:1698) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_12191(class_2813.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_11054(class_2813.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:841) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:168) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:817) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:791) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Ampflower** [comment]
Outstanding issues has been fixed; shall port soon.

**Comment by venaminecraft** [comment]
Thanks 😄

**Comment by Ampflower** [comment]
Sorry for taking a while, but: It has been done.
